export type Deck = {
  cards: { [name: string]: number };
};

export const defaultDecks = {
  Custom: {
    cards: {
      "Random Citizen": 2,
    },
  },
  Green: {
    cards: {
      "Brief Investigation": 1,
      "Induce Avarice": 1,
      "Information Dealer": 1,
      "Strike Down": 1,
      "Local Merchant": 1,
      "Trade Secrets": 2,
      "Stake Capital": 2,
      "Moment of Opportunity": 1,
      "Harassment Campaign": 1,
      "Eager Salesman": 1,
      "Company Salesman": 1,
      "Sneering Financier": 1,
      "Careful Speculation": 1,
      "Bold Investor": 1,
      "Flaunting Aristocrat": 1,
      "Tantalizing Offer": 2,
      "Charismatic Industrialist": 1,
    },
  },
  Orange: {
    cards: {
      "Local Socialite": 1,
      "Eager Employer": 1,
      "Rogue Reporter": 1,
      "Arms Dealer": 1,
      "Gang Up": 2,
      "Ill-fated Operative": 1,
      Coerce: 2,
      Outnumber: 1,
      "The Truth, at Any Cost": 1,
      "Cut-rate Contractor": 2,
      "Smokestack Guide": 1,
      Borrow: 1,
      "Raving Pugilist": 2,
      "Dues Collector": 1,
      "Take Arms": 1,
      "Gismo Inspector": 1,
    },
  },
  Blue: {
    cards: {
      Detain: 2,
      "Gang Up": 1,
      "Induce Avarice": 1,
      "Local Socialite": 1,
      "Information Dealer": 1,
      "Expedited Training": 1,
      "Seek Truth": 1,
      "Snoop Around": 1,
      "Cagey Questioning": 1,
      "Search Warrant": 1,
      "Aspiring Lawman": 2,
      "Frazzled Secretary": 2,
      "Bearer of Lanterns": 1,
      "Contraband Confiscator": 1,
      "Stern Peacekeeper": 1,
      "Prolific Jailer": 2,
    },
  },
  Purple: {
    cards: {
      "Sinister Deal": 2,
      "Local Merchant": 1,
      Frame: 1,
      Subterfuge: 1,
      "Pilfered Intelligence": 2,
      "Examine the Bodies": 1,
      Entice: 1,
      "Shifty Operative": 1,
      "Strike Down": 1,
      "Bad Deal": 1,
      "Moment of Opportunity": 1,
      "New Hire": 2,
      "Gutterside Informer": 1,
      "Undercity Tavernkeep": 1,
      "Partner in Crime": 1,
      "Problem Solver": 2,
    },
  },
};